version: "3.2"
services:
  nginx:
    image: nginx:1.17.8
    ports:
        - 80:80
    volumes:
      - ./nginx-config/site.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app
    networks:
        - laravel
  app:
    build: .
    volumes:
      - ./:/var/www
    ports:
      - 9000:9000
    networks:
        - laravel
  githook_installer:
    build:
      context: .
      dockerfile: 'Dockerfile.githooks'
    volumes:
      - ./.git:/tmp/.git
      - ./hooks:/tmp/hooks
  phpunit:
    image: php:7.4-cli
    volumes:
      - ./:/var/www
    working_dir: /var/www

networks:
  laravel:
